# version: '3.8'  # 新版本Docker Compose不需要version字段

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: fortune-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fortune123456
      MYSQL_DATABASE: fortune_db
      MYSQL_USER: fortune
      MYSQL_PASSWORD: fortune123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - fortune-network

  # Redis缓存
  redis:
    image: redis:6.2-alpine
    container_name: fortune-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fortune-network

  # 后端应用
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: fortune-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=fortune_db
      - MYSQL_USERNAME=fortune
      - MYSQL_PASSWORD=fortune123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - WECHAT_APP_ID=${WECHAT_APP_ID}
      - WECHAT_APP_SECRET=${WECHAT_APP_SECRET}
    depends_on:
      - mysql
      - redis
    networks:
      - fortune-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: fortune-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - fortune-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  fortune-network:
    driver: bridge 