services:
  # MySQL数据库 - 公网版
  mysql:
    image: mysql:8.0
    container_name: bagua-mysql-public
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Fortune2025!Root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-bagua_ai}
      MYSQL_USER: ${MYSQL_USERNAME:-bagua_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Fortune2025!User}
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"  # 绑定到所有网络接口
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/complete-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-Fortune2025!Root}"]
      timeout: 20s
      retries: 5
      interval: 30s

  # Redis缓存 - 公网版
  redis:
    image: redis:7-alpine
    container_name: bagua-redis-public
    restart: unless-stopped
    ports:
      - "6379:6379"  # 绑定到所有网络接口
    volumes:
      - redis_data:/data
    environment:
      TZ: Asia/Shanghai
    command: redis-server --requirepass ${REDIS_PASSWORD:-Fortune2025!Redis}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-Fortune2025!Redis}", "ping"]
      timeout: 10s
      retries: 3
      interval: 30s

  # 后端应用 - 公网版
  backend:
    image: openjdk:17-jdk-slim
    container_name: bagua-backend-public
    restart: unless-stopped
    ports:
      - "8080:8080"  # 绑定到所有网络接口
      - "8081:8081"  # 管理端口
    volumes:
      - ./backend/target:/app
      - ./logs:/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Shanghai
      # 数据库配置
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-bagua_ai}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME:-bagua_user}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD:-Fortune2025!User}
      # Redis配置
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD:-Fortune2025!Redis}
      # AI服务配置
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_API_URL=${DEEPSEEK_API_URL:-https://api.deepseek.com/v1/chat/completions}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL:-deepseek-chat}
      # 微信配置
      - WECHAT_APP_ID=${WECHAT_APP_ID}
      - WECHAT_APP_SECRET=${WECHAT_APP_SECRET}
      # JWT配置
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      # 服务器配置
      - SERVER_ADDRESS=0.0.0.0
    command: >
      sh -c "
      cd /app && 
      java -Xms512m -Xmx1024m -jar *.jar 
      --server.port=8080
      --server.address=0.0.0.0
      --management.server.port=8081
      --management.server.address=0.0.0.0
      --management.endpoints.web.exposure.include=health,info,metrics
      "
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8081/actuator/health || exit 1"]
      timeout: 30s
      retries: 3
      interval: 60s
      start_period: 120s

  # Nginx反向代理 - 公网版
  nginx:
    image: nginx:alpine
    container_name: bagua-nginx-public
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "8081:8081"  # 管理端口
    volumes:
      - ./nginx/nginx.public-http.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
      - ./frontend/dist:/usr/share/nginx/html:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-122.51.104.128}
    depends_on:
      - backend

volumes:
  mysql_data:
  redis_data: 