version: '3.8'

services:
  bagua-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.host
    network_mode: "host"
    volumes:
      - ./backend/target:/app
      - ./logs:/logs
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - SPRING_PROFILES_ACTIVE=prod
    command: >
      sh -c "
      cd /app && 
      /usr/lib/jvm/java-17-openjdk-amd64/bin/java 
      -jar *.jar 
      --server.port=8080
      --spring.datasource.url=jdbc:mysql://localhost:3306/bagua_ai
      --spring.datasource.username=bagua_user
      --spring.datasource.password=your_secure_password
      --spring.redis.host=localhost
      --spring.redis.port=6379
      "
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: bagua_ai
      MYSQL_USER: bagua_user
      MYSQL_PASSWORD: your_secure_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: 