version: '3.8'

services:
  # MySQL数据库 - 使用Docker容器
  mysql:
    image: mysql:8.0
    container_name: bagua-mysql-docker
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: fortune_db
      MYSQL_USER: fortune_user
      MYSQL_PASSWORD: fortune123456
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"  # 使用不同端口避免冲突
    volumes:
      - mysql_docker_data:/var/lib/mysql
      - ./backend/src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    networks:
      - fortune-hybrid
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 后端应用 - 连接Docker MySQL和本地Redis
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: bagua-backend-hybrid
    restart: unless-stopped
    ports:
      - "8081:8080"  # 使用不同端口避免冲突
    environment:
      - SPRING_PROFILES_ACTIVE=hybrid
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=fortune_db
      - MYSQL_USERNAME=fortune_user
      - MYSQL_PASSWORD=fortune123456
      - REDIS_HOST=host.docker.internal  # 连接宿主机Redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=  # 本地Redis无密码
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-your-api-key}
      - WECHAT_APP_ID=${WECHAT_APP_ID:-your-app-id}
      - WECHAT_APP_SECRET=${WECHAT_APP_SECRET:-your-app-secret}
      - JWT_SECRET=hybrid-jwt-secret-key-for-development
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fortune-hybrid
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m

volumes:
  mysql_docker_data:
    driver: local

networks:
  fortune-hybrid:
    driver: bridge 