server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: fortune-mini-app
  
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fortune_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 3000ms

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# 日志配置
logging:
  level:
    com.fortune: debug
    org.springframework.web: info

# 自定义配置
fortune:
  jwt:
    secret: fortune-mini-app-secret-key-2024
    expiration: 86400000
  deepseek:
    api-url: https://api.deepseek.com/v1/chat/completions
    api-key: ${DEEPSEEK_API_KEY:your-deepseek-api-key}
    model: deepseek-chat
    max-tokens: 500
    temperature: 0.7
  wechat:
    app-id: ${WECHAT_APP_ID:your-wechat-app-id}
    app-secret: ${WECHAT_APP_SECRET:your-wechat-app-secret}
